version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - recsys-streaming_kafka_network

  kafka0:
    container_name: kafka0
    build: kafka/
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "users.actions:1:1,recommendations:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka0:9093,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ../.kafka:/var/run/docker.sock
    networks:
      - recsys-streaming_kafka_network

  mock-user-actions-producer:
    build:
      context: mock-producers/
      dockerfile: Dockerfile
    environment:
      - TOPIC=users.actions
      - BOOTSTRAP_KAFKA_SERVER=kafka0:9093
      - MOCK_DATA_PATH=/app/mock_data/users_actions.jsonl
      - SEND_INTERVAL=5
    depends_on:
      - kafka0
    networks:
      - recsys-streaming_kafka_network

  mock-recommendations-producer:
    build:
      context: mock-producers
      dockerfile: Dockerfile
    environment:
      - TOPIC=recommendations
      - BOOTSTRAP_KAFKA_SERVER=kafka0:9093
      - MOCK_DATA_PATH=/app/mock_data/users_ids.jsonl
      - SEND_INTERVAL=5
    depends_on:
      - kafka0
    networks:
      - recsys-streaming_kafka_network

networks:
  recsys-streaming_kafka_network:
    external: true