version: '3.7'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ../recsys_lakehouse/.datalake:/opt/airflow/.datalake
    - ./dags:/opt/airflow/dags
    - ./jobs:/opt/airflow/jobs
    - ./logs:/opt/airflow/logs
    - ./.config/airflow.cfg:/opt/airflow/airflow.cfg
  depends_on:
    - postgres
  networks:
    - recsys-streaming-net
  user: root

services:
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - recsys-streaming-net

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db upgrade && airflow users create --username admin --firstname Recsys --lastname Streaming --role Admin --email recsys@streaming.com --password admin && airflow scheduler"

networks:
  recsys-streaming-net: