name: Docker Image CI

on:
  push:
    branches: [ "test_ci" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./recsys-streaming-ml --tag recsys-streaming-ml:$(date +%s)
